DROP TABLE IF EXISTS ServerSubscriber;
DROP TABLE IF EXISTS ServerRequest;
DROP TABLE IF EXISTS Subscriber;
DROP TABLE IF EXISTS Server;
DROP TABLE IF EXISTS Tariff;

CREATE TABLE Server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias VARCHAR(40) NOT NULL,
    ip_address VARCHAR(16) NOT NULL,
    location VARCHAR(30) NOT NULL,
    flag_code VARCHAR(3) NOT NULL
);

CREATE TABLE Subscriber (
    telegram_id BIGINT PRIMARY KEY,
    telegram_username VARCHAR(50),
    join_date TIMESTAMP NOT NULL
);

CREATE TABLE Tariff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(40) UNIQUE NOT NULL,
    price INTEGER NOT NULL,
    duration INTEGER NOT NULL
);

CREATE TABLE ServerSubscriber (
    server_id BIGINT REFERENCES Server(id),
    subscriber_id BIGINT REFERENCES Subscriber(telegram_id) NOT NULL,
    tariff_id INTEGER REFERENCES Tariff(id) NOT NULL,
    uuid VARCHAR(36) UNIQUE NOT NULL,
    subscription_valid_until TIMESTAMP NOT NULL,
    PRIMARY KEY (server_id, subscriber_id)
);

CREATE TABLE ServerRequest (
    uid VARCHAR(36) PRIMARY KEY,
    telegram_requester_id BIGINT NOT NULL,
    telegram_requester_username VARCHAR(100),
    requested_server BIGINT REFERENCES Server(id) NOT NULL,
    requested_tariff BIGINT REFERENCES Tariff(id) NOT NULL,
    request_date TIMESTAMP NOT NULL
);


INSERT INTO Server (ip_address, alias, location, flag_code) VALUES ('194.120.116.246', 'Tulip', 'Netherlands', 'ND');
INSERT INTO Server (ip_address, alias, location, flag_code) VALUES ('188.130.207.163', 'Croissant', 'France', 'FR');
INSERT INTO Server (ip_address, alias, location, flag_code) VALUES ('188.120.207.153', 'Aurora', 'Finland', 'FIN');
INSERT INTO Tariff (title, price, duration) VALUES ('Bronze', 169, 1);
INSERT INTO Tariff (title, price, duration) VALUES ('Silver', 449, 3);
INSERT INTO Tariff (title, price, duration) VALUES ('Gold', 799, 6);